version: '3.5'

services:
    redis:
        image: redis
        container_name: ${PREFIX}-redis
        networks:
            - app-net

    worker:
        image: ${PREFIX}-worker-img
        container_name: ${PREFIX}-worker
        networks:
            - app-net
        depends_on:
            - redis
        
    app-db:
        image: mysql
        container_name: ${PREFIX}-app-db
        networks:
            - app-net
        environment:
            - MYSQL_ROOT_PASSWORD=root
        
    daemon:
        image: ${PREFIX}-daemon-img
        container_name: ${PREFIX}-daemon
        networks:
            - app-net
        environment:
            - DB_URL=app-db
        command: [ "/opt/src/common/wait-for-it.sh", "app-db:3306", "--", "python", "/opt/src/daemon.py" ]
        depends_on:
            - app-db
            - redis
        
    customer:
        image: ${PREFIX}-customer-img
        container_name: ${PREFIX}-customer
        networks:
            - app-net
        environment:
            - DB_URL=app-db
        command: [ "/opt/src/common/wait-for-it.sh", "app-db:3306", "--", "python", "/opt/src/customer.py" ]
        depends_on:
            - app-db


networks:
  app-net:
      external:
        name: ${PREFIX}-app-net