version: '3'

services:
    redis:
        image: redis
#        ports:
#            - 6379:6379
        networks:
          - app-net
    worker:
        image: worker-img
        networks:
            - app-net
        depends_on:
            - redis
    app-db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        networks:
            - app-net
    daemon:
        image: daemon-img
        environment:
            - DB_URL=app-db
        depends_on:
            - app-db
            - redis
        command: [ "/opt/src/common/wait-for-it.sh", "app-db:3306", "--", "python", "/opt/src/daemon.py" ]
        networks:
            - app-net
    customer:
        image: customer-img
        environment:
            - DB_URL=app-db
        depends_on:
            - app-db
        command: [ "/opt/src/common/wait-for-it.sh", "app-db:3306", "--", "python", "/opt/src/customer.py" ]
        networks:
            - app-net

networks:
  app-net: