version: '3'

services:
    redis:
        image: redis
#        ports:
#            - 6379:6379
        networks:
          - app-net
    worker:
        image: worker-img
        networks:
            - app-net

networks:
  app-net: