version: '3.5'

services:
    store-db:
        image: mysql
        container_name: store-db
        networks:
            - store-daemon-net
            - store-customer-net
            - store-admin-net
            - store-db-init-net
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - store-data:/var/lib/mysql
    
    store-db-init:
        image: store-db-init
        container_name: store-db-init
        networks:
            - store-db-init-net
        environment:
            - DB_URL=store-db
        command: [ "/opt/src/common/wait-for-it.sh", "store-db:3306", "-s", "-q", "-t", "60",  "--", "python", "/opt/src/migrate.py" ]
        depends_on:
            - store-db
    
    store-redis:
        image: redis
        container_name: store-redis
        networks:
            - store-worker-net
            - store-daemon-net
        
    store-customer:
        image: store-customer
        container_name: store-customer
        networks:
            - store-customer-net
        ports:
            - "5001:5000"
        environment:
            - DB_URL=store-db
        command: [ "/opt/src/common/wait-for-it.sh", "store-db:3306", "-s", "-q", "-t", "60", "--", "python", "/opt/src/customer.py" ]
        depends_on:
            - store-db
    
    store-worker:
        image: store-worker
        container_name: store-worker
        networks:
            - store-worker-net
        ports:
            - "5002:5000"
        depends_on:
            - store-redis
        environment:
            - DB_URL=store-db

    store-daemon:
        image: store-daemon
        container_name: store-daemon
        networks:
            - store-daemon-net
        environment:
            - DB_URL=store-db
        command: [ "/opt/src/common/wait-for-it.sh", "store-db:3306", "-s", "-q", "-t", "60", "--", "python", "/opt/src/daemon.py" ]
        depends_on:
            - store-db
            - store-redis

    store-admin:
        image: store-admin
        container_name: store-admin
        networks:
            - store-admin-net
        ports:
            - "5003:5000"
        environment:
            - DB_URL=store-db
        command: [ "/opt/src/common/wait-for-it.sh", "store-db:3306", "-s", "-q", "-t", "60", "--", "python", "/opt/src/admin.py" ]
        depends_on:
            - store-db

        

networks:
    store-worker-net:
        external:
            name: store-worker-net
    store-admin-net:
        external:
            name: store-admin-net
    store-customer-net:
        external:
            name: store-customer-net
    store-daemon-net:
        external:
            name: store-daemon-net
    store-db-init-net:
        external:
            name: store-db-init-net

        
volumes:
    store-data:
        external:
            name: store-data
